baseURL = "https://slavaqq.github.io/"
languageCode = "cs"
title = "SlavaQQ"
theme = "ezhil"

paginate = 5
summaryLength = 10

[taxonomies]
    tag = "tags"

[author]
    name = "Slava"

[params]
    subtitle= "osobní zápisník"

[[menu.main]]
    identifier = "tags"
    name = "Štítky"
    url = "/tags/"
    weight = 1

[[menu.main]]
    identifier = "archives"
    name = "Archiv"
    url = "/posts/"
    weight = 2

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"
